### ISSUE TITLE
Feature request Dockerfile inside docker

### ISSUE THREAD

**Issue by homdx** [JonasT/p4a-build-spaces#10]
@JonasT Hello!)
Thank you for this convenient and interesting project.

I propose to implement the functionality of adding the Docker file itself inside the docker.
Those. Put the total Docker file into docker:
ADD Docker-current /

This will allow reuse of this script Dockerfile in other projects.

**Comment by JonasT** [comment]
I'm not 100% sure what you have in mind, but something that may help you is to output the Dockerfile:

```
p4aspaces print-dockerfile p4a-py2-api28ndk21 --map-to-user 1000 > Dockerfile
```
... and then you can just use it or modify it in any way you like!

**Comment by homdx** [comment]
Great!
Yes, everyone understood me correctly.
Maybe add to readme? How to see the docker file?
>p4aspaces print-dockerfile p4a-py2-api28ndk21 --map-to-user 1000

**Comment by JonasT** [comment]
All commands are always listed in `p4aspacs --help`:

```
$ p4aspaces --help
usage: p4aspaces [-h] action ...

[...]
  action      The p4a-build-spaces action out of "cmd", "list-envs", "print-
              dockerfile", "shell"   << FULL LIST HERE
```
The readme is lacking a bit behind, sorry :joy: I should update it more

**Comment by JonasT** [comment]
This is documented in the readme now: https://github.com/JonasT/p4a-build-spaces#output-generated-dockerfile so I'll close this. Let me know if there's anything else missing!
